Sprint1
Nereee/E4_DB_T5 pull request #1
Opened 2024-04-22 06:21 UTC by ibai-elorrieta

Datubase Scripta eginda eta Datu batzuk insertatuta

2024-04-22 07:37 UTC, Nereee requested changes
Batetik datu basearen sorrera scripta eta bestetik insertekin beste fitxategia.

2024-04-22 07:37 UTC, Nereee commented on spotify script.sql
> +	create table erreprodukzioak(
Bezero bat ezabatzen baduzue erreprodukzioak ezabatuko dituzue? Nola kudeatuko dituzue ondoren estadistikak?¿

2024-04-22 07:37 UTC, Nereee commented on spotify script.sql
> +	foreign key (hizkuntza) references hizkuntza(idHizkuntza)
Hizkuntza bat ezin daiteke ezabatu edo aldatu baldin eta bezeroren batek bere preferentzietan aukeratu badu aurretiaz¿?

2024-04-22 07:37 UTC, Nereee commented on spotify script.sql
> +	idBezero varchar(5) primary key,
Ondo iruditzen zait kode alfanumerikoa izatea. Baina erabaki nola kudeatuko duzuen mahai gaineko aplikaziotik. Aldatzea erabakitzen baduzue ere ondo egongo da.

2024-04-23 05:59 UTC, Nereee requested changes

2024-04-23 05:59 UTC, Nereee commented on spotify script.sql
> +	foreign key (hizkuntza) references hizkuntza(idHizkuntza) ON DELETE CASCADE ON UPDATE CASCADE
Hizkuntza bat ezabatzen baduzue, bezeroa ezabatuko duzue? Horixe da nahi duzuena?

2024-04-23 05:59 UTC, Nereee commented on spotify script.sql
> +	foreign key (idBezero) references bezero(idBezero),
Ezingo duzue bezero bat ezabatu baldin eta bezero horrek erreprodukzioak egin dituen. Hori da nahi duzuen funtzionamendua?

2024-04-25 06:05 UTC, Nereee requested changes

2024-04-25 06:05 UTC, Nereee commented on spotify script.sql
> +	foreign key (idBezero) references bezero(idBezero),
Bezeroak ezabatu daitezke zuen datu basean? Kudeaketa hori egingo duzue? Horren arabera baliozkoa izango da, edo ez, foreign key honen murrizketaren definizioa. Pentsatu eta erantzun iezaidazue

2024-04-25 10:39 UTC, OlandaJon commented on spotify script.sql
> +	foreign key (idBezero) references bezero(idBezero),
Aldaketak eginda

2024-04-25 10:55 UTC, Nereee approved these changes

2024-04-25 10:55 UTC, merged